### ISSUE TITLE
scenario manager: weather data including forecasts to be stored in one file

### ISSUE THREAD

**Issue by sdlumpp** [tum-ewk/lemlab#16]
Weather data is currently stored in a central directory and accessed by all prosumers when required. Data is split into one time series file with measured weather data and a subdirectory containing a rolling-horizon forecast time series for each simulation timestep.

In order to avoid parallel file access conflicts, or alternatively wait times, this data is to be assigned to each Multiprocessing worker as an initialization argument. The data can then be accessed from memory by each agent without disk access being required.

**Task:**
Weather data including forecasts must be stored in a single data structure in the scenario directory.

Alternative strucutres should be investigated. The proposed solution needs to be described here and discussed with at least one admin before the status "ready" may be assigned.

**Describe alternatives you've considered**

**Implementation details**
Concise description of final implementation. List of modules, functions, variables (if used outside of the module) that were edited, added, removed.

**Comment by TUM-Doepfert** [comment]
**Alternative approaches that were considered**
- Create a 2D array with pandas using an extra column to specify the z-direction to create a 3D-array with a 2D setup --> saved as feather file
- Use numpy to create an unlabeled 3D-array --> feather file
- Use xarray-package to create a labeled --> netCDF file

**Comment by TUM-Doepfert** [comment]
**Implemented approach**
- lemlab will use a multiindex 2D array with pandas as it is the best compromise between speed, file size and familiarity with packages
- Possible input formats will be feather ".ft" and netcdf ".nc"
- netcdf files will be converted in the scenario manager to a pandas dataframe

For further information about the decision process, see the attached Excel file [weather_file_comparison.xlsx](https://github.com/tum-ewk/lemlab/files/8089761/weather_file_comparison.xlsx)

**Implementation details**
The dataframe will use a 2-level multiindex. The first index "ts_now" contains the current timestamp for which the current value and the forecast values are for. The second index "ts_delivery". The values are selected based on these indices.

**Comment by sdlumpp** [comment]
Solution accepted and implemented.

**Comment by sdlumpp** [comment]
Solution accepted and implemented.
