### ISSUE TITLE
FEHLER:  Relation »info_user« existiert nicht

### ISSUE THREAD

**Issue by hamzaaitabdel** [tum-ewk/lemlab#24]
**Describe the bug**
`psycopg2.errors.UndefinedTable: FEHLER:  Relation »info_user« existiert nicht` when running sim_3_run.py

**To Reproduce**
1. navigate to ./PycharmProjects/lemlab/code_examples
2. execute sim_1_create_scenario.py, followed by sim_3_run.py

**Screenshots**
![Alt text](https://i.postimg.cc/mDF7J6pH/image.png "a title")
![Alt text](https://i.postimg.cc/7Y1nqdH1/image.png "a title")

**Comment by sdlumpp** [comment]
This is a known problem, please follow the instructions on line 589 of db connection

**Comment by sdlumpp** [comment]
Diagnosis: Versioning problem with sqlalchemy. Manual commented fix in db_connection to be replaced with updated try/except.

In future please attach "conda list" report to bug reports.

This bug issue succeeded by implementation issue.
